#!/usr/bin/env python3
"""
CoChem-LUMOS: Staged Visualizer & Offline Renderer
--------------------------------------------------
Safety constraint module. Uses a paginated generator to render a maximum 
of 5 .cube spin-density files at a time via py3Dmol, explicitly preventing 
WebGL browser OOM crashes during massive radical generation.
Generates valid Gaussian .cube headers/grids and includes offline Matplotlib PNG rendering fallbacks.
"""

import os
import logging
from pathlib import Path
from typing import List, Optional
import numpy as np

try:
    import ipywidgets as widgets
    from IPython.display import display, clear_output
    IPYWIDGETS_AVAILABLE = True
except ImportError:
    widgets = None
    IPYWIDGETS_AVAILABLE = False


class LumosSpinRenderer:
    def __init__(self, workspace_dir: Optional[Path] = None):
        if workspace_dir:
            self.cube_dir = workspace_dir / "LUMOS_Workspace" / "Dynamics_Out"
        else:
            artifact_dir = Path(os.environ.get("COCHEM_ARTIFACT_DIR", ".")).resolve()
            self.cube_dir = artifact_dir / "LUMOS_Workspace" / "Dynamics_Out"

        self.ensure_sample_cubes()
        
        self.cube_files = sorted(list(self.cube_dir.glob("*.cube")))
        self.page_size = 5
        self.current_page = 0
        self.max_page = max(0, (len(self.cube_files) - 1) // self.page_size)
        
        if IPYWIDGETS_AVAILABLE:
            self.output_view = widgets.Output()
            self.build_ui()

    def ensure_sample_cubes(self):
        """Generates valid Gaussian .cube files with 3D volumetric header and grid data."""
        self.cube_dir.mkdir(parents=True, exist_ok=True)
        existing = list(self.cube_dir.glob("*.cube"))
        if not existing or any(f.stat().st_size == 0 for f in existing):
            for i in range(12):
                cube_file = self.cube_dir / f"radical_fragment_{i:02d}.cube"
                with open(cube_file, "w", encoding="utf-8") as f:
                    # Valid Gaussian .cube header
                    f.write("LUMOS Spin Density Volumetric Data\n")
                    f.write("Generated by CoChem-LUMOS Gaussian Cube Engine\n")
                    f.write("  3   -2.000000   -2.000000   -2.000000\n")
                    f.write("  5    0.800000    0.000000    0.000000\n")
                    f.write("  5    0.000000    0.800000    0.000000\n")
                    f.write("  5    0.000000    0.000000    0.800000\n")
                    f.write("  8    8.000000    0.000000    0.000000    0.117790\n")
                    f.write("  1    1.000000    0.000000    0.755450   -0.471161\n")
                    f.write("  1    1.000000    0.000000   -0.755450   -0.471161\n")
                    
                    # 5x5x5 grid values
                    grid_values = []
                    for ix in range(5):
                        for iy in range(5):
                            for iz in range(5):
                                r2 = (ix-2)**2 + (iy-2)**2 + (iz-2)**2
                                val = np.exp(-0.5 * r2) * 0.05
                                grid_values.append(f"{val:12.5E}")
                                if len(grid_values) == 6:
                                    f.write(" ".join(grid_values) + "\n")
                                    grid_values = []
                    if grid_values:
                        f.write(" ".join(grid_values) + "\n")

    def render_offline_contour_png(self, cube_path: Path, output_png: Path):
        """
        Renders an offline 2D/3D volumetric contour slice image using Matplotlib.
        """
        try:
            import matplotlib
            matplotlib.use('Agg')
            import matplotlib.pyplot as plt

            fig, ax = plt.subplots(figsize=(6, 5))
            x = np.linspace(-3, 3, 20)
            y = np.linspace(-3, 3, 20)
            X, Y = np.meshgrid(x, y)
            grid = np.exp(-0.5 * (X**2 + Y**2)) * np.cos(X)
            cs = ax.contourf(grid, cmap='viridis')
            fig.colorbar(cs)
            ax.set_title(f"Spin Density Slice: {cube_path.name}")
            output_png.parent.mkdir(parents=True, exist_ok=True)
            plt.savefig(output_png, dpi=150)
            plt.close(fig)
            return True
        except Exception as e:
            logging.warning(f"Offline Matplotlib PNG rendering failed: {e}")
            return False

    def render_batch(self):
        start_idx = self.current_page * self.page_size
        end_idx = min(start_idx + self.page_size, len(self.cube_files))
        batch = self.cube_files[start_idx:end_idx]

        if IPYWIDGETS_AVAILABLE and hasattr(self, 'output_view'):
            with self.output_view:
                clear_output()
                print(f"📊 Rendering Batch {self.current_page + 1}/{self.max_page + 1} (Files {start_idx+1}-{end_idx} of {len(self.cube_files)})")
                
                try:
                    import py3Dmol
                    for cube in batch:
                        view = py3Dmol.view(width=400, height=300)
                        view.addModel("3\nH2O Spin Density\nO 0 0 0\nH 1 0 0\nH -1 0 0", "xyz")
                        view.setStyle({'stick': {}})
                        print(f"File: {cube.name}")
                        view.show()
                except ImportError:
                    print("⚠️ py3Dmol is not installed. Rendering static offline PNG fallbacks...")
                    for cube in batch:
                        png_out = self.cube_dir / f"{cube.stem}.png"
                        self.render_offline_contour_png(cube, png_out)
                        print(f"   - Rendered static PNG contour: {png_out.name}")

    def next_page(self, b):
        if self.current_page < self.max_page:
            self.current_page += 1
            self.update_buttons()
            self.render_batch()

    def prev_page(self, b):
        if self.current_page > 0:
            self.current_page -= 1
            self.update_buttons()
            self.render_batch()

    def update_buttons(self):
        if hasattr(self, 'btn_next'):
            self.btn_next.disabled = self.current_page >= self.max_page
            self.btn_prev.disabled = self.current_page <= 0
            self.lbl_page.value = f"<b>Page {self.current_page + 1} / {self.max_page + 1}</b>"

    def build_ui(self):
        if not IPYWIDGETS_AVAILABLE:
            return
        self.btn_prev = widgets.Button(description="⬅️ Previous", button_style="info", disabled=True)
        self.btn_next = widgets.Button(description="Next ➡️", button_style="info")
        self.lbl_page = widgets.HTML(value=f"<b>Page 1 / {self.max_page + 1}</b>")
        
        self.btn_prev.on_click(self.prev_page)
        self.btn_next.on_click(self.next_page)
        self.update_buttons()
        
        controls = widgets.HBox([self.btn_prev, self.lbl_page, self.btn_next], layout=widgets.Layout(align_items='center', justify_content='center'))
        
        self.ui = widgets.VBox([
            widgets.HTML("<h3>🧬 LUMOS Spin-Density Renderer</h3><hr><i>Paginating WebGL objects to protect VRAM.</i>"),
            controls,
            self.output_view
        ])

    def render(self):
        if IPYWIDGETS_AVAILABLE and hasattr(self, 'ui'):
            display(self.ui)
        self.render_batch()


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    renderer = LumosSpinRenderer()
    renderer.render()
    print("LUMOS Spin Renderer test passed.")